# Assignment 4: Predicting 2022 citations based on all the 2017-2021 citations.

Kavya Shah

SUID: 330126500

PIN: 68

Email ID: kshah28@syr.edu

ref-link1: https://www.geeksforgeeks.org/back-propagation-with-tensorflow/

ref-link2: https://machinelearningmastery.com/implement-backpropagation-algorithm-scratch-python/

and some from chatgpt 

In [1]:
# Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


In [2]:
# Upload Data Set

dataset = pd.read_csv('61-70.csv')
dataset.head()

univ_rank first_initial last_initial cit_2017  cit_2018  cit_2019  \
0         61             S            B      239       291       298   
1         61             C            F      811       774       677   
2         61             J            F      262       279       264   
3         61             D            F       53        54       148   
4         61             L            G        8        35       200   

   cit_2020  cit_2021  cit_2022  h_index  i_10_index  
0       360       447       397       15          17  
1       514       562       431       55         107  
2       215       208       217       10          10  
3       151       280       344       15          16  
4       437       560       741        8           7

In [3]:
# Copy dataset into data frame
df = dataset.copy()
df.head()

univ_rank first_initial last_initial cit_2017  cit_2018  cit_2019  \
0         61             S            B      239       291       298   
1         61             C            F      811       774       677   
2         61             J            F      262       279       264   
3         61             D            F       53        54       148   
4         61             L            G        8        35       200   

   cit_2020  cit_2021  cit_2022  h_index  i_10_index  
0       360       447       397       15          17  
1       514       562       431       55         107  
2       215       208       217       10          10  
3       151       280       344       15          16  
4       437       560       741        8           7

In [4]:
# Explore and analyze data:
df.shape

(100, 11)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   univ_rank      100 non-null    int64 
 1   first_initial  100 non-null    object
 2   last_initial   100 non-null    object
 3   cit_2017       100 non-null    object
 4   cit_2018       100 non-null    int64 
 5   cit_2019       100 non-null    int64 
 6   cit_2020       100 non-null    int64 
 7   cit_2021       100 non-null    int64 
 8   cit_2022       100 non-null    int64 
 9   h_index        100 non-null    int64 
 10  i_10_index     100 non-null    int64 
dtypes: int64(8), object(3)
memory usage: 8.7+ KB


In [6]:
# Currently the cit_2017 Dtype is object hence converting it to Dtype int64 

df['cit_2017'] = df['cit_2017'].str.replace(',', "").astype(int)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   univ_rank      100 non-null    int64 
 1   first_initial  100 non-null    object
 2   last_initial   100 non-null    object
 3   cit_2017       100 non-null    int64 
 4   cit_2018       100 non-null    int64 
 5   cit_2019       100 non-null    int64 
 6   cit_2020       100 non-null    int64 
 7   cit_2021       100 non-null    int64 
 8   cit_2022       100 non-null    int64 
 9   h_index        100 non-null    int64 
 10  i_10_index     100 non-null    int64 
dtypes: int64(9), object(2)
memory usage: 8.7+ KB


In [8]:
# describe will give the statistical information of each column in dataset
df.describe()

univ_rank     cit_2017     cit_2018     cit_2019     cit_2020  \
count  100.000000   100.000000   100.000000   100.000000   100.000000   
mean    65.500000   276.950000   297.210000   286.510000   299.510000   
std      2.886751   342.992104   420.642469   338.664802   348.377292   
min     61.000000     0.000000     0.000000     0.000000     3.000000   
25%     63.000000    52.750000    53.250000    66.000000    84.500000   
50%     65.500000   145.000000   131.000000   130.500000   148.500000   
75%     68.000000   374.250000   349.500000   406.000000   425.750000   
max     70.000000  1721.000000  2942.000000  1771.000000  1776.000000   

         cit_2021     cit_2022     h_index  i_10_index  
count   100.00000   100.000000  100.000000   100.00000  
mean    306.37000   373.800000   26.430000    50.69000  
std     347.44367   746.157957   14.797116    41.38357  
min       7.00000     2.000000    5.000000     5.00000  
25%      77.75000    84.750000   14.750000    16.75000  
50%     156.50000   148.000000   24.000000    41.00000  
75%     456.00000   424.500000   35.250000    75.50000  
max    1804.00000  6902.000000   66.000000   223.00000

In [9]:
# Check if there are any duplicates in the dataset
df.isna().sum()

univ_rank        0
first_initial    0
last_initial     0
cit_2017         0
cit_2018         0
cit_2019         0
cit_2020         0
cit_2021         0
cit_2022         0
h_index          0
i_10_index       0
dtype: int64

In [10]:
# Splitting the dataset into 80% training and 20% testing 

x = df[['cit_2017', 'cit_2018', 'cit_2019', 'cit_2020', 'cit_2021']]
y = df[['cit_2022']]

# Splitting your DataFrame 'df' into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size = 0.80, test_size=0.2, random_state=42)


In [11]:
x_train.head()

cit_2017  cit_2018  cit_2019  cit_2020  cit_2021
55         4        11        13        33        27
88        88        88        71       123        83
26       114       125       130       197       178
42       924       948      1015       950       850
69       165       145       121       152       115

In [12]:
x_train.shape

(80, 5)

In [13]:
x_test.head()

cit_2017  cit_2018  cit_2019  cit_2020  cit_2021
83      1251      1061       994       908       836
53        79        91        93       103        77
70       187       126       111       136        76
45       169       210       261       291       398
44       149       163       137       126       124

In [14]:
x_test.shape

(20, 5)

In [15]:
y_train.head()

cit_2022
55        43
88       102
26       195
42       734
69       143

In [16]:
y_train.shape

(80, 1)

In [17]:
y_test.head()

cit_2022
83       782
53        81
70        80
45       404
44        89

In [18]:
y_test.shape

(20, 1)

In [19]:
# Normalizing both the train and test data

from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler = MinMaxScaler(feature_range=(0, 1))

In [21]:
x_train = scaler.fit_transform(x_train)
x_train

array([[2.32423010e-03, 2.38257318e-03, 7.34048560e-03, 1.69204738e-02,
        1.11296605e-02],
       [5.11330622e-02, 2.85908781e-02, 4.00903444e-02, 6.76818951e-02,
        4.22927101e-02],
       [6.62405578e-02, 4.11844792e-02, 7.34048560e-02, 1.09419064e-01,
        9.51585977e-02],
       [5.36897153e-01, 3.21307012e-01, 5.73122530e-01, 5.34122955e-01,
        4.69115192e-01],
       [9.58744916e-02, 4.79918312e-02, 6.83229814e-02, 8.40383531e-02,
        6.01001669e-02],
       [5.92678675e-02, 3.33560245e-02, 4.85601355e-02, 8.06542583e-02,
        7.62381747e-02],
       [2.81231842e-01, 1.65078285e-01, 3.47826087e-01, 3.56457981e-01,
        3.44462994e-01],
       [1.23184195e-01, 5.13955071e-02, 7.34048560e-02, 5.92216582e-02,
        6.45520312e-02],
       [1.91748983e-02, 9.18992512e-03, 2.59740260e-02, 2.03045685e-02,
        2.72676683e-02],
       [0.00000000e+00, 7.48808713e-03, 8.18746471e-02, 1.91201354e-01,
        3.37785198e-01],
       [2.14991284e-02, 1.4295

In [22]:
x_test = scaler.transform(x_test)
x_test

array([[ 7.26902963e-01,  3.59768550e-01,  5.61264822e-01,
         5.10434292e-01,  4.61324430e-01],
       [ 4.59035445e-02,  2.96119809e-02,  5.25127047e-02,
         5.64015792e-02,  3.89538119e-02],
       [ 1.08657757e-01,  4.15248468e-02,  6.26764540e-02,
         7.50141004e-02,  3.83973289e-02],
       [ 9.81987217e-02,  7.01157250e-02,  1.47374365e-01,
         1.62436548e-01,  2.17584864e-01],
       [ 8.65775712e-02,  5.41184479e-02,  7.73574252e-02,
         6.93739425e-02,  6.51085142e-02],
       [ 0.00000000e+00,  7.48808713e-03,  3.55731225e-02,
         3.72250423e-02,  4.84140234e-02],
       [ 5.81057525e-02,  2.45064670e-02,  5.25127047e-02,
         6.03496898e-02,  5.78742348e-02],
       [ 2.20220802e-01,  1.21170865e-01,  1.81253529e-01,
         1.72588832e-01,  1.53032832e-01],
       [ 2.20801859e-02,  2.34853642e-02,  7.11462451e-02,
         1.17315285e-01,  1.69727323e-01],
       [ 1.38872748e-01,  9.76855003e-02,  1.68266516e-01,
         2.01353638e-01

In [23]:
# Importing tensorflow

import tensorflow as tf
from random import seed
from random import random

lol = len(x_train[0])
lol

5

In [24]:
# Defining the neural network 5-3-1 architecture using Tensor Flow:

seed(1)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(3, activation = 'relu' , input_shape = (len(x_train[0]),)),
    tf.keras.layers.Dense(1, activation = 'relu')
    
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 18        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 22 (88.00 Byte)
Trainable params: 22 (88.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
# defining hyper parameters:
learning_rate = 0.1
model.compile( tf.keras.optimizers.SGD(learning_rate), loss = 'mean_absolute_error')
model.fit(x_train, y_train, epochs = 1000 , shuffle = False)
    

Epoch 1/1000
3/3 [==============================] - 0s 2ms/step - loss: 408.0026
Epoch 2/1000
3/3 [==============================] - 0s 661us/step - loss: 407.4985
Epoch 3/1000
3/3 [==============================] - 0s 1ms/step - loss: 406.8688
Epoch 4/1000
3/3 [==============================] - 0s 854us/step - loss: 406.0095
Epoch 5/1000
3/3 [==============================] - 0s 823us/step - loss: 404.7505
Epoch 6/1000
3/3 [==============================] - 0s 1ms/step - loss: 402.6991
Epoch 7/1000
3/3 [==============================] - 0s 903us/step - loss: 399.1964
Epoch 8/1000
3/3 [==============================] - 0s 879us/step - loss: 393.2070
Epoch 9/1000
3/3 [==============================] - 0s 870us/step - loss: 383.2852
Epoch 10/1000
3/3 [==============================] - 0s 941us/step - loss: 368.6349
Epoch 11/1000
3/3 [==============================] - 0s 1ms/step - loss: 350.6204
Epoch 12/1000
3/3 [==============================] - 0s 870us/step - loss: 330.1990
Epoch 13/

In [26]:
# Calculate MAE

from sklearn.metrics import mean_absolute_error
y_pred = model.predict(x_test)
mean_absolute_error = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mean_absolute_error}")


1/1 [==============================] - 0s 25ms/step
Mean Absolute Error (MAE): 37.75960168838501


In [27]:
y_pred 

array([[692.8738  ],
       [ 91.59355 ],
       [ 66.454506],
       [401.33453 ],
       [122.34772 ],
       [110.199554],
       [108.72528 ],
       [259.09006 ],
       [335.62357 ],
       [458.32962 ],
       [319.7795  ],
       [ 20.921854],
       [ 58.752457],
       [ 19.690155],
       [ 33.98474 ],
       [628.07434 ],
       [104.128235],
       [106.52757 ],
       [600.3913  ],
       [ 23.404865]], dtype=float32)

In [28]:
y_test

cit_2022
83       782
53        81
70        80
45       404
44        89
39        69
22        96
80       297
10       422
0        397
18       344
30        42
73        88
33         2
90        53
4        741
76       129
77        95
12       509
31         9

In [29]:
# 0.1  - 37.75960168838501
# 0.01 - 50.229731702804564
# 0.001 - 180.74897499084472 
# 0.6 - 122.49656753540039